export const ADD_COMMENT = "ADD_COMMENT";

export const LOAD_TECHARTICLES = "LOAD_TECHARTICLES";
export const TECHARTICLES_LOADING = "TECHARTICLES_LOADING";
export const TECHARTICLES_FAILED = "TECHARTICLES_FAILED";

export const LOAD_TECHARTICLES_COMMENTS = "LOAD_TECHARTICLES_COMMENTS";
export const TECHARTICLES_COMMENTS_LOADING = "TECHARTICLES_COMMENTS_LOADING";
